config/routes.rb
Rails.application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]

  root "pages#home"
  get 'pages/contact'
  get 'pages/about'
  get 'pages/help'











end

app/views/pages/about.html.erb
<h1>About Page</h1>
<p>This is the about page for <a href="http://railstutorial.org/"> Ruby on Rails application</p>

app/views/pages/contact.html.erb
<h1>Contact Page</h1>
<p>This is the contact page <a href="http://railstutorial.org/"> on Rails application</p>

app/views/pages/help.html.erb
<h1>Help</h1>
<p>Get help on Ruby on Rails Tutorial at the 
	<a href="http://railstutorial.org/help">Rails Tutorial help page </a>
	To get hlep on this sample app, see the 
	<a href="http://railstutorial.org/book">Rails Tutorial book</a>
</p>

app/views/pages/home.html.erb
<% if signed_in? %>
	<table class="front" summary="For signed-in users">
		<tr>
			<td class="main">
				<h1 class="micropost">What's up?</h1>
				<%= render 'shared/micropost_form' %>
				<%= render 'shared/feed' %>
			</td>
			<td class="sidebar round">
				<%= render 'shared/user_info' %>
				<%= render 'shared/stats' %>
			</td>
		</tr>
	</table>
<% else %>
	<h1>Home Page</h1>
	<p>This is the home page <a href="http://railstutorial.org/"> on Rails application</p>
	<%= link_to "Sign up now!", new_user_path %>
<% end %>