config/routes.rb
Rails.application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]

  root "pages#home"
  get 'pages/contact'
  get 'pages/about'
  get 'pages/help'











end

app/views/layouts/_footer.html.erb
<footer>
	<nav class="round">
		<ul>
			<li><%= link_to "About", pages_about_path %></li>
			<li><%= link_to "Contact", pages_contact_path %></li>
			<li><%= link_to "News", 'http://news.railstutorial.org/'%></li>
			<li><%= link_to "Rails Tutorial", 'http://railstutorial.org'%></li>
		</ul>
</footer>

app/views/layouts/_header.html.erb
<header>
	<nav class ="round">
		<ul>
			<li><%= link_to "Home", root_path %> </li>
			<li><%= link_to "Help",  pages_help_path %> </li>
			<% if signed_in? %>
				<li><%= link_to "Profile", user_path(current_user) %></li>
				<li><%= link_to "All Users", users_path %></li>
				<li><%= link_to "Sign out", session_path(current_user), method: :delete %></li>
				<li><%= link_to "Edit", edit_user_path(current_user)%></li>
			<% else %>
				<li><%= link_to "Sign in", new_session_path %>
			<% end %>
		</ul>
	</nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'bluepring/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= @title %></title>
		<%= csrf_meta_tag %>
		<%= render 'layouts/stylesheets' %>
		<%= javascript_include_tag 'application' %>
	</head>
	<body>
		<div class="container">
			<header>
				<%= link_to image_tag("logo.png", :alt => "Sample App", :class => "round"), root_path %>
				<%= render 'layouts/header' %>
			</header>
			<section class="round">
				<% flash.each do |key, value| %>
					<div class = "flash <%= key %>"><%= value %></div>
				<% end %>
				<%= yield %>
			</section>
			<%= render 'layouts/footer' %>
			<%= debug(params) if Rails.env.development? %>
		</div>
	</body>
</html>